name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy: 
      matrix:
        include:
          - os: macos-latest
            solipathCommand: ./solipath
          - os: ubuntu-latest
            solipathCommand: ./solipath
          - os: windows-latest
            solipathCommand: .\solipath
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        ${{matrix.solipathCommand}} bundler install
        ${{matrix.solipathCommand}} bundle exec rake
